# Generated by Django 4.2.6 on 2023-10-24 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_asset_updated_at_alter_episode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 21, 56, 35, 904800), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 21, 56, 35, 906694), null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 21, 56, 35, 900127), null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 21, 56, 35, 901094), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 21, 56, 35, 901075), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
