# Generated by Django 4.2.6 on 2023-10-26 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_asset_updated_at_alter_episode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 28, 50, 495433), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='resolution',
            field=models.CharField(default='1920X1020', max_length=9),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 28, 50, 497456), null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 28, 50, 490487), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 28, 50, 491460), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 28, 50, 491442), null=True),
        ),
    ]
