# Generated by Django 4.2.6 on 2023-10-26 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_note_updated_at_alter_project_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 23, 31, 37, 403711), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 31, 37, 404766), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 23, 31, 37, 404748), null=True),
        ),
    ]
