# Generated by Django 4.2.6 on 2023-10-28 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_step_end_date_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 14, 49, 28, 190160), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 28, 14, 49, 28, 191151), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 28, 14, 49, 28, 191132), null=True),
        ),
    ]
