# Generated by Django 4.2.6 on 2023-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilstep',
            name='short_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#ffffff', max_length=100, unique=True),
        ),
    ]
